name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0, v1.1, etc.

permissions:
  contents: write  # Required for creating releases and uploading assets

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Create release packages
      run: |
        node build.js package
        
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Udemy Speed Controller ${{ steps.get_version.outputs.VERSION }}
          
          ### Installation
          
          **Chrome:**
          1. Download `udemy-speed-controller-chrome-${{ steps.get_version.outputs.VERSION }}.zip`
          2. Extract the zip file
          3. Go to `chrome://extensions/`
          4. Enable "Developer mode"
          5. Click "Load unpacked" and select the extracted folder
          
          **Firefox:**
          1. Download `udemy-speed-controller-firefox-${{ steps.get_version.outputs.VERSION }}.zip`
          2. Extract the zip file
          3. Go to `about:debugging`
          4. Click "This Firefox" → "Load Temporary Add-on"
          5. Select the `manifest.json` file from the extracted folder
          
          ### Features
          - Control video playback speed from 0.5x to 8x
          - Persistent speed settings across page navigation
          - Works with Udemy's single-page application
          - Cross-browser compatibility (Chrome & Firefox)
          
          ### What's Changed
          - See commit history for detailed changes
        draft: false
        prerelease: false
        files: |
          dist/udemy-speed-controller-chrome-${{ steps.get_version.outputs.VERSION }}.zip
          dist/udemy-speed-controller-firefox-${{ steps.get_version.outputs.VERSION }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 